[package]
name = "mdbook-rss-feed"
version = "1.5.0"
edition = "2024"
authors = ["T. Sawyer saylesss88@github.com"]
license = "Apache-2.0"
description = "An mdBook preprocessor that generates a full-content RSS/Atom feed from your book"
repository = "https://github.com/saylesss88/mdbook-rss-feed"
readme = "README.md"
keywords = ["mdbook", "rss", "feed", "preprocessor", "blog"]
categories = [
	"command-line-utilities",
	"development-tools::build-utils",
	"web-programming",
]
homepage = "https://github.com/saylesss88/mdbook-rss-feed"
documentation = "https://docs.rs/mdbook-rss-feed"
exclude = [".github/*", ".gitignore", "book/*"]

[lib]
name = "mdbook_rss_feed"
path = "src/lib.rs"

[[bin]]
name = "mdbook-rss-feed"
path = "src/bin/mdbook-rss-feed.rs"

[dependencies]
anyhow = {version = "1.0.104", default-features = false}
walkdir = "2"
rss = "2.1.0"
serde = {version = "1", features = ["serde_derive"], default-features = false}
chrono = {version = "0.4", features = ["std"], default-features = false}
pulldown-cmark = {version = "0.13", features = [
	"html",
], default-features = false}
serde_json = "1"
atom_syndication = {version = "0.12.10", default-features = false, optional = true}
yaml_serde = "0.10.4"
thiserror = "2.0.19"

[features]
default = []
json-feed = []
atom = ["dep:atom_syndication"]
